### ISSUE TITLE
Get Location from the Home Zone in hass.config

### ISSUE THREAD

**Issue by askpatrickw** [Pirate-Weather/pirate-weather-ha#241]
### Describe the feature

This is related to #46 which is a request for a templating integration.

This conversation on the HA Community may be useful.
https://community.home-assistant.io/t/how-does-an-integration-access-has-set-location/734850

## Read Location from Home Assistant's Location

This feature is a simpler request which is for the integration to use the Home Zone as the source of the location. This is exposed on the [HASS object under hass.config](https://developers.home-assistant.io/docs/dev_101_config/?_highlight=latitude).

On every run, this integration should read the latitude and longitude from hass.config and that would solve the mainline stationary and mobile cases.

This should be the default behavior for new installs.
For existing installs, the existing specified location can be stored as the advanced config.

### Location 

One might want to use Pirate Weather to see the weather at some other location, in that case the integration can expose manually setting location in advanced configuration which is normally hidden from the user. 

### Language

Hass.config exposes language and advanced setting could be used an override, or the HASS language could be used instead. The README says only English is supported though, so maybe just remove this and use the HA one if is needed in the future.

### Units

Hass.config exposes units. It may be that the HA Units are not specific enough, and you would want and override to enable "SI". I believe UK, CA, US would be covered.

## Related: Updating Location using homeassistant.set_location

Mobile uses can use homeassistant.set_location to set the location. Below is an example of using Peplink Mobile Router's GPS (captured from API calls) to do so.

```yaml
alias: update_peplink_gps
trigger:
  - platform: state
    entity_id: sensor.peplink_gps
action:
  - service: device_tracker.see
    data:
      dev_id: van_luna
      gps:
        - "{{ state_attr('sensor.peplink_gps', 'latitude') }}"
        - "{{ state_attr('sensor.peplink_gps', 'longitude') }}"
  - service: homeassistant.set_location
    data_template:
      latitude: "{{ state_attr('sensor.peplink_gps', 'latitude') }}"
      longitude: "{{ state_attr('sensor.peplink_gps', 'longitude') }}"
```

### Home Assistant version

latest

### Integration version

latest

### Acknowledgements

- [X] I have searched this repository and [API Repository](https://github.com/Pirate-Weather/pirateweather/) to see if the feature has already been requested.
- [X] This featre request is sepecific to the HA Integration.
- [X] I have written an informative title.
