### ISSUE TITLE
Feature Request: Allow Templating in Configuration

### ISSUE THREAD

**Issue by tdvantine** [Pirate-Weather/pirate-weather-ha#46]
Currently the entry in configuration.yaml requires you to put your static location in: (broad location used here, yes I understand I could/should use a !secret here, but meh) 
```
weather:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: '39'
    longitude: '-104'
    mode: "daily"
    name: PirateWeather
```
This works wonderful for home use, and I would say a good 95%+ of installations. However, I personally have a outlier case, as well as I am sure those that use HA for their RV or boat, etc would like this as well. I use HA to automate things on a touring show (think theatrical touring) and we are at a different city every week, being able to template the location would be amazing so we could get the weather for what ever city we are in that week.
An example of what the entry would look like:
```
weather:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: {{states.person.<NAME>.attributes.latitude}}
    longitude: {{states.person.<NAME>.attributes.longitude}}
    mode: "daily"
    name: PirateWeather
```

I have found some work-arounds to this, using a rest sensor to poll the api, but this wont do as it polls the api on every update of location instead of every 15mins/configured amount of time in the sensor. 

I have a home instance (HA Core on Ubuntu) and the touring one (HAOS on a Pi) so I would be more than happy and willing to test out anything you need. I am also open to any other ideas to get this working.

**Comment by alexander0042** [comment]
Hi,

Thanks for trying out this service and opening this issue! That's a really interesting use case (I love hearing how people are using this service), and definitely something that would be worth adding. 

At the moment, I'm in the middle of a re-write of this entire integration. It started out as just trying to allow setup via the web GUI config flow, but in order to do that the code had to be asynchronous, which led to all sorts of complications! The good news is that I almost have this working, and it should modernize most of the code base here, The way you've described the template it should "just work", but I remain skeptical. 

One quick thing that would help here is if you could try adding a single variable rest sensor, since you've already started down that road a little bit. If you check out this issue: <https://github.com/alexander0042/pirate-weather-ha/issues/4#issuecomment-1129034675>, I have instructions on how to create one for a single variable, Since the rest sensor supports templates (I think), it'd be worth testing that with temperature just to make sure that one part of it is updating.

**Comment by tdvantine** [comment]
```
sensor:
  - platform: rest
    name: PW_1Day_Precip
    scan_interval: 15
    resource: https://api.pirateweather.net/forecast/<key>/<lat>,<long>,-86400?units=ca
    value_template: "{{ float(value_json.daily.data[0].precipAccumulation) }}"
    unit_of_measurement: "cm"
```
Is very very similar to the rest sensor I had set up. I will add in the `scan_interval:` and do some testing to see if that clears up the constant api call everytime my location is reported again. Will post back later today with the results and excact code block used. 

I personally find the pirate weather intergration the best one avaible, a lot of the others lack features or you have to pay for them unlike PW.

**Comment by alexander0042** [comment]
Thanks, keep me posted!

This sort of feedback is really great to hear- it really bothered me that most weather forecasts come from government agencies, but then we have to go through poorly documented cooperate APIs to access the data, so I wanted to do something to fix it. It shouldn't be such a mystery what AccuWeather means by "percent of precipitation", but it is for some reason! Along the way, the Dark Sky syntax seemed to work perfectly well, and let me leverage a ton of existing code out there (like this integration).

**Comment by tdvantine** [comment]
https://twitter.com/kleverlands/status/1338927247126827009?s=20&t=k4Ag7l-W7MY6PPG18cOdbw
```
- platform: rest
  resource_template: !secret pirate_rest_resource
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precip_probability
    - precip_type
    - humidity
    - cloud_cover
    - nearest_storm_distance
    - precip_intensity
    - wind_speed
  name: pirateweather_api_test
  value_template: 'OK'
  ```
Didn't update on the 15min mark, as well as its missing some of the data.
![image](https://user-images.githubusercontent.com/56764154/170178906-b14a132f-6f6e-41f3-a470-fd29c1d5f434.png)
Just noticed as I was typing, the attributes don't line up correctly. So for right this second, its just the update at the 15 min mark that isn't happening

**Comment by tdvantine** [comment]
Corrected the JSON Attributes and solved that "problem".
![image](https://user-images.githubusercontent.com/56764154/170180488-e06e042a-0be9-4b80-aa6d-16c25d325897.png)

**Comment by tdvantine** [comment]
```
- platform: rest
  resource_template: !secret pirate_rest_resource
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precipProbability
    - precipType
    - humidity
    - cloudCover
    - nearestStormDistance
    - precipIntensity
    - windSpeed
  name: pirateweather_api_test
  value_template: 'OK
```
Updates every 15 mins and does NOT update when the device tracker updates location so that's perfect. Now, too bad it isn't intergrated into a weather entity to use the weather cards. 

The resource:
```
pirate_rest_resource: 'https://dev.pirateweather.net/forecast/<API>/{{states.person.tristan_van_tine.attributes.latitude}},{{states.person.tristan_van_tine.attributes.longitude
```

**Comment by tdvantine** [comment]
Been playing around and I believe that using the rest calls just isn't going to work as nicely. Having a hard time getting forecast to show in a weather card.

So far I have this for the weather.dynamic_weather sensor:
```
weather:
  - platform: template
    name: "Dynamic Weather"
    unique_id: 472658229893
    # attribution: "Powered by PirateWeather"
    condition_template: "{{ state_attr('sensor.pirateweather_api_test', 'summary') }}"
    temperature_template: "{{ state_attr('sensor.pirateweather_api_test', 'temperature') | float }}"
    humidity_template: "{{ state_attr('sensor.pirateweather_api_test', 'humidity') | float }}"
    pressure_template: "{{ state_attr('sensor.pirateweather_api_test', 'pressure') }}"
    wind_speed_template: "{{ state_attr('sensor.pirateweather_api_test', 'windSpeed') }}"
    ozone_template: "{{ state_attr('sensor.pirateweather_api_test', 'ozone') }}"
    visibility_template: "{{ state_attr('sensor.pirateweather_api_test', 'visibility') }}"
    forecast_template: "{{ state_attr('pirateweather_api_forcast', 'data') }}"
```
![image](https://user-images.githubusercontent.com/56764154/170913810-8e63606c-daf7-4434-9199-38bae51d204e.png)

Which all pulls in correctly, other than forecast.

I have this working great for current weather conditions:
```
- platform: rest
  resource_template: !secret pirate_rest_resource
  name: pirateweather_api_test
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precipProbability
    - precipType
    - humidity
    - cloudCover
    - nearestStormDistance
    - precipIntensity
    - windSpeed
    - visibility
    - ozone
    - windBearing
    - pressure
  value_template: 'OK'
  ```
  
![image](https://user-images.githubusercontent.com/56764154/170913858-56f68a5d-e65e-41d5-832a-79fbcd1392d5.png)

  
  I tried to combine the call using the below, but it didnt work for the forecast once again:
  ```
  rest:
  - scan_interval: 900
    resource_template: !secret pirate_rest_resource
    sensor:
      - name: "pirateweather_api_current"
        json_attributes_path: "$.currently"
        value_template: "OK"
        json_attributes:
          - summary
          - temperature
          - precipProbability
          - precipType
          - humidity
          - cloudCover
          - nearestStormDistance
          - precipIntensity
          - windSpeed
          - visibility
          - ozone
          - windBearing
          - pressure
      - name: "pirateweather_api_forcast"
        json_attributes_path: "$.daily"
        value_template: "OK"
        json_attributes:
          - data
```
![image](https://user-images.githubusercontent.com/56764154/170913709-00150a49-f253-4021-91e0-61bcf377e5b5.png)
![image](https://user-images.githubusercontent.com/56764154/170913751-11b3ac2a-c6bf-48db-8941-f7fb56fdeca0.png)
